"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard from './dashboard.bones.json'
import _payment_table from './payment-table.bones.json'

registerBones({
  "dashboard": _dashboard,
  "payment-table": _payment_table,
})
